version: '3.7'
services:
  db:
    image: registry.diginfra.net/mysql:5.6
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mgw
      - MYSQL_USER=browser
      - MYSQL_PASSWORD=browsie
  app:
    image: registry.diginfra.net/php-apache:5.6
    restart: always
    ports:
      - 8000:80
    environment:
      - MGW_DB=mgw
      - MGW_DB_HOST=db
      - MGW_MYSQL_USER=browser
      - MGW_MYSQL_PASSWORD=browsie
      - MGW_PROTOCOL=http
      - MGW_PORT=8000